const projects = {
    "luxiemdatingsim": {
        "title": "Light The Way • Luxiem Dating Sim",
        "desc": "From August 2022 to April 2023, I have been part of the project <em>\"Light The Way • Luxiem Dating Sim\"</em> in Simporiem Studios as Mysta's route programmer. This Dating Sim has been made with Ren'Py a Python based programming language.<br>This game was initially created for the first anniversary of the 4th talents wave from Nijisanji: Luxiem.<br><br><b>NOTE</b>: This game is a FANgame and is not affiliated to Anycolor Inc.",
        "link": "<iframe class=\"frame\" frameborder=\"0\"  src=\"https://itch.io/embed/1843062?border_width=0&amp;bg_color=191817&amp;fg_color=ffffff&amp;link_color=bdbdbd&amp;border_color=191817\" width=\"600\" height=\"100%\">><a href=\"https://simporiem-studios.itch.io/light-the-way\" target=\"_blank\">Light the Way by Simporiem Studios</a></iframe>",
        "img": "<div class=\"grid\"><img src=\"../img/ltwlds_im2.png\" width=\"100%\" class=\"img_proj\"><img src=\"../img/screenshot0119.webp\" width=\"100%\" class=\"img_proj\"><img src=\"../img/screenshot0159.webp\" width=\"100%\" class=\"img_proj\"><img src=\"../img/game_itch.png\" width=\"100%\" class=\"img_proj\"></div>",
        "linkres":"<a href=\"https://simporiem-studios.itch.io/light-the-way\" class=\"linkd\" target=\"_blank\">Link to the project</a>",
        "useful_links":"",
    },
    "optionguide": {
        "title": "Luxiem Dating Sim • Option Guide",
        "desc": "In order to present the options of the game \"Light The Way • Luxiem Dating Sim\", I participated into making an online guide. A website entirely made by hand.",
        "link": "<a href = \"https://natsbarnett.github.io/luxiem-dating-sim-options-guide/\" class=\"linkd\" target=\"_blank\">Link to the website</a>",
        "img": "<img src=\"../img/option_guide_im.png\" width=\"50%\" class=\"img_proj\">",
        "linkres":"",
        "useful_links":"",
    },
    "genshintest": {
        "title": "Genshin Impact Experience Test",
        "desc": "For fun, I decided to create a Genshin Test. This was made with HTML, CSS and some JavaScript to calculate the final score and give a meaning to the results. This has been inspired by this test: <a href= \"https://hakuhakuwu.github.io/How-Messed-Up-is-Your-Fanfiction-Taste/fanfictiontest.html\" class=\"wh_link\">How Messed Up Is Your Fanfiction Taste</a>",
        "link": "<a href=\"https://natsbarnett.github.io/genshin-test/\" class=\"linkd\" target=\"_blank\">Link to the website</a>",
        "img": "<img src=\"../img/ft_test_im.png\" width=\"50%\" class=\"img_proj\">",
        "linkres":"",
        "useful_links":"",
    },
    "ltwoptl": {
        "title": "Light the Way OP 【Promo MV】• French TL",
        "desc": "As we prepared the closed captions of the original version, we also prepared some translations. I have been working on the French Translation of this MV.",
        "link": "<iframe class=\"frame\" width=\"720\" height=\"360\" src=\"https://www.youtube.com/embed/rXX2gnxzVCg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>",
        "img": "<img src=\"../img/op_tl_meme.jpg\" width=\"25%\" class=\"img_proj\">",
        "linkres":"<a href=\"https://www.youtube.com/watch?v=rXX2gnxzVCg\" class=\"linkd\" target=\"_blank\">Link to the video</a>",
        "useful_links":"",
    },
    "clips": {
        "title": "Clipping Vtubers",
        "desc": "In my free time, I have the habit to clip some VTubers I enjoy watching.",
        "link": "<div class=\"grid\"><iframe class=\"vids\" width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/5BAY9KFlGH4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe><iframe class=\"vids\" width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/_epBBZxtA4o\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe><iframe class=\"vids\" width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/WWIVcrCpLcw\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe></div>",
        "img": "<img src=\"../img/meme_clip.jpg\" width=\"25%\" class=\"img_proj\">",
        "linkres":"<a href=\"https://www.youtube.com/playlist?list=PL40UFul3xcLaeiSQaqWlfCJacpTKn8SQd\" class=\"linkd\" target=\"_blank\">Link a Youtube playlist</a>",
        "useful_links":"",
    },
    "portfolio": {
        "title": "My Portfolio",
        "desc": "To put all my work inside the same place, I decided to make a portfolio. This website is still not entirely responsive yet but I'm working on it as much as I can! I am trying to put all of my knowledge I acquire while in school into this website. Maybe one day, this website will be available and adapted for mobile screens, for now, it's preferable to visit it on pc screens.",
        "link": "",
        "img": "<img src=\"../img/portfolio_img.png\" width=\"50%\" class=\"img_proj\">",
        "linkres":"",
        "useful_links":"",
    },
    
    "bsddaily": {
        "title": "BSD Daily Facts Archive",
        "desc":"To archive a Twitter account of a friend (@BsdDailyFacts), I decided, with them, to create a website. To create it, I used a JavaScript data base and some scripts in JavaScript.",
        "link": "<a href = \"https://natsbarnett.github.io/bsd-daily-facts-archive/\" class=\"linkd\" target=\"_blank\">Link to the website</a>",
        "img":"<div class=\"grid\"><img src = \"../img/bsd_daily_facts_1.png\" width=\"100%\" class=\"img_proj\"><img src = \"../img/bsd_daily_facts_2.png\" width=\"100%\" class=\"img_proj\"></div>",
        "linkres":"",
        "useful_links":"",
    },
}